package bg.tu_sofia.fdiba.ticketing.integration;// Generated by Selenium IDE
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class FDIBATest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fDIBA() {
    driver.get("http://programm.fdiba.tu-sofia.bg/bg/?q=plan_group");
    driver.manage().window().setSize(new Dimension(1440, 796));
    driver.findElement(By.name("week")).click();
    {
      WebElement dropdown = driver.findElement(By.name("week"));
      dropdown.findElement(By.xpath("//option[. = '9 (18.11 - 22.11)']")).click();
    }
    driver.findElement(By.name("group")).click();
    {
      WebElement dropdown = driver.findElement(By.name("group"));
      dropdown.findElement(By.xpath("//option[. = 'INF 2021 1']")).click();
    }
    driver.findElement(By.cssSelector(".find-btn")).click();

    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > .busy:nth-child(3) > b")).getText(), is("3109 - лекция\nDoz. A. Aleksieva"));
  }
}
